# install.ps1
# One-liner installer for lenovo-backlight-controller.
# Usage:
#   iwr -useb https://raw.githubusercontent.com/r00bertos1/lenovo-backlight-controller/main/install.ps1 | iex
#
# Steps:
#   1. Banner.
#   2. Ensure AutoHotkey v2 is installed (winget or fallback).
#   3. Download repo zip from GitHub main branch, extract to $InstallDir.
#   4. Generate devices.ahk from devices.json.
#   5. Run detect-device.ahk if no device matches current hardware.
#   6. Register/refresh Task Scheduler entry.
#   7. Stop any prior controller, start fresh.

$ErrorActionPreference = 'Stop'

$RepoUrl    = 'https://github.com/r00bertos1/lenovo-backlight-controller'
$ZipUrl     = "$RepoUrl/archive/refs/heads/main.zip"
$InstallDir = Join-Path $env:LOCALAPPDATA 'lenovo-backlight-controller'
$AhkPath    = Join-Path $env:LOCALAPPDATA 'Programs\AutoHotkey\v2\AutoHotkey64.exe'
$TaskName   = 'LenovoBacklightController'
$UserId     = "$env:USERDOMAIN\$env:USERNAME"

Write-Host ''
Write-Host '=== Lenovo Backlight Controller - installer ==='
Write-Host ''

# --- 1. Ensure AutoHotkey v2 -----------------------------------------------
if (-not (Test-Path $AhkPath)) {
    Write-Host 'AutoHotkey v2 not found. Installing via winget...'
    try {
        winget install --id AutoHotkey.AutoHotkey --silent --accept-source-agreements --accept-package-agreements
        if (-not (Test-Path $AhkPath)) {
            throw "winget reported success but $AhkPath still missing."
        }
    } catch {
        Write-Host "winget install failed: $_"
        Write-Host 'Please install AutoHotkey v2 manually: https://www.autohotkey.com/'
        exit 1
    }
}
Write-Host "  AutoHotkey v2 at: $AhkPath"

# --- 2. Download repo zip --------------------------------------------------
Write-Host ''
Write-Host 'Downloading repo from GitHub...'
$tmpZip = Join-Path $env:TEMP "lenovo-backlight-controller-$([guid]::NewGuid()).zip"
Invoke-WebRequest -Uri $ZipUrl -OutFile $tmpZip -UseBasicParsing
Write-Host "  Downloaded $((Get-Item $tmpZip).Length) bytes"

# --- 3. Extract to install dir ---------------------------------------------
if (Test-Path $InstallDir) {
    # Stop running controller before overwriting files.
    # Process.Path returns the AHK runtime; the script path lives in CommandLine,
    # which requires CIM/WMI.
    Get-CimInstance Win32_Process -Filter "Name = 'AutoHotkey64.exe'" |
        Where-Object { $_.CommandLine -like "*$InstallDir*" } |
        ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }
    Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    Remove-Item -Recurse -Force $InstallDir
}
$tmpExtract = Join-Path $env:TEMP "lbc-extract-$([guid]::NewGuid())"
Expand-Archive -Path $tmpZip -DestinationPath $tmpExtract -Force
# Repo zip contains a single top folder like "lenovo-backlight-controller-main".
$inner = Get-ChildItem $tmpExtract | Where-Object { $_.PSIsContainer } | Select-Object -First 1
Move-Item -Path $inner.FullName -Destination $InstallDir
Remove-Item -Recurse -Force $tmpExtract
Remove-Item -Force $tmpZip
Write-Host "  Installed to: $InstallDir"

# --- 4. Generate devices.ahk from devices.json -----------------------------
Write-Host ''
Write-Host 'Generating devices.ahk from devices.json...'
$jsonPath = Join-Path $InstallDir 'devices.json'
$ahkOutPath = Join-Path $InstallDir 'devices.ahk'
$json = Get-Content $jsonPath -Raw | ConvertFrom-Json

$lines = @()
$lines += '; Auto-generated by install.ps1 from devices.json - do not edit.'
$lines += '; Re-generate by re-running install.ps1.'
$lines += ''
$lines += 'global DEVICES := ['
$entries = @()
foreach ($d in $json.devices) {
    $pairs = @()
    foreach ($prop in $d.PSObject.Properties) {
        $key = $prop.Name
        # AHK v2 string escapes: ` (backtick) is the escape char, NOT backslash.
        # Embedded " becomes `" ; embedded ` becomes `` . Backslashes are literal.
        $val = $prop.Value -replace '`', '``' -replace '"', '`"'
        $pairs += "        `"$key`", `"$val`""
    }
    $entries += "    Map(`n" + ($pairs -join ",`n") + "`n    )"
}
$lines += ($entries -join ",`n")
$lines += ']'
Set-Content -Path $ahkOutPath -Value ($lines -join "`n") -Encoding UTF8
Write-Host "  Generated: $ahkOutPath"

# --- 5. Detect device or prompt --------------------------------------------
# Trust that DEVICES contains a match for common hardware. If user's device
# isn't in the list, controller.ahk will MsgBox an instruction at startup.
# The user can run tools\detect-device.ahk to add their device.

# --- 6. Register Task Scheduler entry --------------------------------------
Write-Host ''
Write-Host 'Registering scheduled task...'
$existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($existing) {
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}

$ctrlPath  = Join-Path $InstallDir 'controller.ahk'
$action    = New-ScheduledTaskAction -Execute $AhkPath -Argument ('"' + $ctrlPath + '"')
$trigger   = New-ScheduledTaskTrigger -AtLogOn -User $UserId
$principal = New-ScheduledTaskPrincipal -UserId $UserId -LogonType Interactive -RunLevel Limited
$settings  = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -ExecutionTimeLimit (New-TimeSpan -Hours 0)

Register-ScheduledTask `
    -TaskName    $TaskName `
    -Description 'Auto keyboard backlight controller for Lenovo laptops' `
    -Action      $action `
    -Trigger     $trigger `
    -Principal   $principal `
    -Settings    $settings | Out-Null
Write-Host "  Registered task: $TaskName (At log on of $UserId)"

# --- 7. Start now ----------------------------------------------------------
Write-Host ''
Write-Host 'Starting controller...'
Start-Process -FilePath $AhkPath -ArgumentList ('"' + $ctrlPath + '"')
Start-Sleep -Seconds 1
$proc = Get-CimInstance Win32_Process -Filter "Name = 'AutoHotkey64.exe'" |
    Where-Object { $_.CommandLine -like "*$InstallDir*" } | Select-Object -First 1
if ($proc) {
    Write-Host "  Running, PID $($proc.ProcessId)"
} else {
    Write-Host '  WARNING: controller did not appear in process list. Check Event Viewer or run it manually.'
}

Write-Host ''
Write-Host '=== Install complete ==='
Write-Host ''
Write-Host 'Controller running. Enable Windows Night Light to test:'
Write-Host '  Settings -> System -> Display -> Night Light -> On'
Write-Host ''
Write-Host 'Uninstall:'
Write-Host '  iwr -useb https://raw.githubusercontent.com/r00bertos1/lenovo-backlight-controller/main/uninstall.ps1 | iex'
Write-Host ''
